name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        pip install -e .
        pytest tests/
    
    - name: Build package
      run: |
        python -m build
    
    - name: Check package
      run: |
        twine check dist/*
    
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: GitUp ${{ github.ref }}
        body: |
          ## What's Changed
          
          See [CHANGELOG.md](https://github.com/CallMeChewy/GitUp/blob/main/CHANGELOG.md) for details.
          
          ## Installation
          
          ```bash
          pip install gitup==${{ github.ref_name }}
          ```
          
          ## Quick Start
          
          ```bash
          gitup bootstrap my-project --template=python-web
          ```
          
          Full documentation: [docs/QUICKSTART.md](https://github.com/CallMeChewy/GitUp/blob/main/docs/QUICKSTART.md)
        draft: false
        prerelease: false
    
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload dist/*